name: OreSpawners
version: 0.5.3
main: RKAbdul\OreSpawners\Main
authors: [RKAbdul, Wanter]
api: 4.0.0

commands:
 orespawner:
  description: Give ore spawner.
  usage: "/orespawner [ore] [amount] [player]"
  aliases: ["os"]
  permission: "orespawner.give"
